services:
  server:
    build: ./server
    container_name: server-container
    tty: true

  client1:
    build: ./client
    container_name: client1-container
    tty: true
    ports:
      - "8080:5000"

  client2:
    build: ./client
    container_name: client2-container
    tty: true
